### ISSUE TITLE
训练时报错，AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by Altiumleaf** [TonyZ1Min/yolo-for-k210#7]
当它在进行训练的时候，会发生报错：Anaconda3\envs\yolo\lib\site-packages\keras\engine\saving.py", line 1004, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by dextercai** [comment]
This problem may occur if the version of h5py is too high. Script works well with 2.10 version

**Comment by bd7jat** [comment]
> This problem may occur if the version of h5py is too high. Script works well with 2.10 version

Thanks a lot ,i followed your way to get things done !

**Comment by DoudouMee** [comment]
> This problem may occur if the version of h5py is too high. Script works well with 2.10 version

Thank you， help a lot

**Comment by Spirit-77** [comment]
thanks
